import React, { useMemo, useState } from 'react';
import { LanguageContext } from './LanguageContextInstance.jsx';

const COPY = {
  am: {
    label: 'አማርኛ 🇪🇹',
    magicLine: 'ብቻ ይናገሩ — ስራ ስራዎችን ያገኛል፣ ያመልክታል እና ያስተያየታል።',
    micPlaceholder: 'ክህሎትዎን፣ ልምዱን እና ቦታዎን ይናገሩ…',
    headerSearchPlaceholder: 'ስራዎችን በድምፅ ወይም በጽሁፍ ይፈልጉ…',
    mapApplyCta: 'ለመመዝገብ ይናገሩ',
    ratingsTitle: 'ደረጃ እና አስተያየት',
    ratingsSubtitle: 'ለተጠናቀቁ ስራዎች ደረጃ ስጡ እና መተማመንን ያበረታቱ።',
    rateButton: 'ደረጃ ስጥ',
    voiceRatingTitle: 'የድምፅ አስተያየት',
    voiceRatingSubtitle: 'አስተያየትዎን ይናገሩ፣ ከዚያ ጽሁፉን ያስተካክሉ።',
    close: 'ዝጋ',
    cancel: 'ተወው',
    submitRating: 'ደረጃ ላክ',
    tapToSpeak: 'ለመናገር ይንኩ',
    listening: 'በማዳመጥ ላይ… አሁን ይናገሩ',
    transcribing: 'በመጻፍ ላይ…',
    feedbackLabel: 'አስተያየት',
    speakLabel: 'ይናገሩ',
    jobPostTitle: 'ስራ ለጥፍ',
    jobPostSubtitle: 'በድምፅ መጀመሪያ ስራ ማስታወቂያ፡ አንድ ጊዜ ይግለጹ፣ ስራ ቅጹን ትሞላለች።',
    voiceModeLabel: 'የድምፅ ሁነታ',
    voiceModeHint: 'ይናገሩ፡ ሚና/ስራ፣ ቦታ፣ ክፍያ፣ ቀን/ሰዓት።',
    voiceModeTap: 'ስራውን ለመግለጽ ማይኩን ይንኩ',
    voiceModeExample: 'ምሳሌ፡ “ነገ በቦሌ 2 ማጽጃ ሰራተኞች እፈልጋለሁ፣ 500 ብር።”',
    fieldTitle: 'ርዕስ',
    fieldCategory: 'ምድብ',
    fieldLocation: 'ቦታ',
    fieldSalary: 'ደመወዝ (ብር)',
    fieldDescription: 'መግለጫ',
    dashboard: 'ዳሽቦርድ',
    availableJobs: 'የሚገኙ ስራዎች',
    talkToSira: 'ከሥራ ጋር ይነጋገሩ',
    voiceToCV: 'ድምፅ ወደ ሲቪ',
    jobMap: 'የስራ ካርታ',
    history: 'ታሪክ',
    ratings: 'ደረጃዎች',
    profile: 'መገለጫ',
    employerDashboard: 'የቀጣሪ ዳሽቦርድ',
    employerSub: 'ብልጥ ማገናኛ። አስተማማኝ ውሎች። እንከን የለሽ ክፍያዎች።',
    postNewJob: 'አዲስ ስራ ልጥፍ',
    yourOpenings: 'የእርስዎ ክፍት የስራ መደቦች',
    aiMatchmaking: 'የአርቴፊሻል ኢንተለጀንስ (AI) ማገናኛ',
    topCandidates: 'ለተመረጠው ፕሮጀክት ምርጥ እጩዎች',
    noAppsFoundJob: 'ለዚህ ስራ ምንም ማመልከቻ አልተገኘም',
    postJob: 'ስራ ለጥፍ',
    applicants: 'አመልካቾች',
    adminDashboard: 'የአድሚን ዳሽቦርድ',
    scamLog: 'የማታለል ምዝገባ',
    systemLanguage: 'የስርዓት ቋንቋ',
    login: 'ግባ',
    register: 'ተመዝገብ',
    logout: 'ውጣ',
    search: 'ፈልግ',
    notifications: 'ማሳወቂያዎች',
    settings: 'ማስተካከያዎች',

    welcomeBack: 'እንኳን ደህና መጡ!',
    aiMatchingActive: 'የአርቴፊሻል ኢንተለጀንስ (AI) ማገናኛ ገባሪ ነው',
    voiceHuntingJobs: 'የእርስዎ የድምፅ ረዳት በአቅራቢያዎ ያሉ ስራዎችን እየፈለገ ነው።',
    clickVoiceSira: 'ስራ ድምፅን ለመጠቀም ይጫኑ',
    talkToFindJobs: 'ስራዎችን ለማግኘት ይናገሩ',
    weeklyEarnings: 'የሳምንት ገቢ',
    calculatedSoon: 'በቅርቡ ይሰላል',
    workerRating: 'የሰራተኛ ደረጃ',
    completedJobsCount: 'የተጠናቀቁ ስራዎች',
    activeApplications: 'ንቁ ማመልከቻዎች',
    liveFromHistory: 'ከታሪክ በቀጥታ የተወሰደ',
    bestMatchesForYou: 'ለእርስዎ ምርጥ ተዛማጆች',
    viewAll: 'ሁሉንም ይዩ',
    noMatchesYet: 'እስካሁን ምንም ተዛማጅ አልተገኘም።',
    voiceSearchMapHint: 'የድምፅ ፍለጋን ይሞክሩ ወይም ስራዎችን ለመፈለግ ካርታውን ይክፈቱ።',
    generateVoiceCv: 'የድምፅ ሲቪ (Voice-CV) ያዘጋጁ',
    voiceCvSubtitle: 'ስራ-AI ከ30 ሰከንድ የድምፅ ቅጂ የእርስዎን ሙያዊ መገለጫ እንዲገነባ ይፍቀዱለት።',
    startNow: 'አሁን ይጀምሩ',
    nearbyJobs: 'በአቅራቢያ ያሉ ስራዎች',
    openJobMap: 'የየስራ ካርታ ይክፈቱ',
    exploreJobs: 'ስራዎችን ያስሱ',
    detailsArrow: 'ዝርዝሮች →',
    speakThreeLanguagesHint: 'በአማርኛ፣ በአፋን ኦሮሞ ወይም በእንግሊዝኛ ይናገሩ። እርምጃ ከመውሰድዎ በፊት ስራ የሰማውን ማስተካከል ይችላሉ።',
    tapToSpeakHint: 'ለመናገር ይንኩ። ከ~10 ሰከንድ በኋላ በራሱ ይቆማል።',
    transcribedTextEditable: 'የተገለበጠ ጽሑፍ (ሊስተካከል የሚችል)',
    voiceBecomesCvTitle: 'የእርስዎ ድምፅ ሲቪዎ ይሆናል',
    voiceFirstCapture: 'ቀጥታ የድምፅ ቀረጻ',
    tapMicAndSpeak: 'ማይክሮፎኑን ነክተው ይናገሩ',
    whatSiraHeard: 'ስራ የሰማው',
    extractedSkills: 'የተለዩ ክህሎቶች',
    speakExampleHint1: 'እንደዚህ ማለት ይችላሉ፡ “እኔ መጋኛ አካባቢ የ3 ዓመት ልምድ ያለኝ ቧንቧ ሰራተኛ ነኝ።”',
    speakExampleHint2: '“እኔ የቤት ሰራተኛ ነኝ፣ ቦሌ እኖራለሁ…”',
    applicationHistoryTitle: 'የማመልከቻ ታሪክ',
    trackHistorySubtitle: 'እያንዳንዱን ማመልከቻ፣ ቅጥር እና ማጠናቀቂያ በአንድ ቦታ ይከታተሉ።',
    noApplicationsYet: 'እስካሁን ምንም ማመልከቻ የለም።',
    walletAndEarningsTitle: 'የእርስዎ ቦርሳ እና ገቢ',
    walletSubtitle: 'ቀሪ ሂሳብዎን፣ የሂሳብ መግለጫ ታሪክዎን ይከታተሉ እና ወደ ባንክ ማስተላለፍ ይጠይቁ።',
    withdrawFunds: 'ገንዘብ አውጣ',
    availableBalance: 'የሚገኝ ቀሪ ሂሳብ',
    readyForImmediateWithdrawal: 'ወዲያውኑ ለማውጣት ዝግጁ የሆነ',
    totalLifetimeEarned: 'በአጠቃላይ የተገኘ ጠቅላላ ገቢ',
    fromJobAllocations: 'ከተጠናቀቁ የስራ ድልድሎች የተገኘ',
    inTransferProcessing: 'በማስተላለፍ ሂደት ላይ ያለ',
    cashoutEventsAwaiting: 'በሂደት ላይ ያሉ የገንዘብ ማውጣት ክስተቶች',
    statementLedger: 'የግብይት መዝገብ መግለጫ',
    noTransactionsLogged: 'በዚህ አካውንት ላይ እስካሁን የተመዘገበ ግብይት የለም።',
    failedToLoadTransactions: 'የግብይት ታሪክን መጫን አልተሳካም',
    bioLabel: 'ስለ እኔ',
    skillsLabel: 'ክህሎቶች',
    noSkillsAdded: 'ምንም ክህሎት አልተጨመረም።',
    experienceLabel: 'የስራ ልምድ',
    yearsExperience: 'ዓመት የሥራ ልምድ',
    preferredLanguageLabel: 'የተመረጠ ቋንቋ',
    aiAgentPreferences: 'የአይ (AI) ወኪል ምርጫዎች',
    autoMatchingAndOneClick: 'ራስ-ሰር ማገናኘት እና ባለአንድ ጠቅታ ማመልከቻዎች',
    autoApplyLabel: 'ራስ-ሰር ማመልከቻ (Auto-Apply)',
    noJobSelected: 'ምንም ስራ አልተመረጠም',
    scanningDatabase: 'የመረጃ ቋቱን በመፈተሽ ላይ...',
    aiRecommendedMatch: 'በስራ የተመከረ',
    verifiedBadge: 'የተረጋገጠ',
    kmAway: 'ኪ.ሜ ርቀት',
    matchPercentage: 'ተዛማጅነት',
    hiringProgress: 'እየቀጠረ ነው...',
    hireAction: 'ቅጠር',
    backToJobs: 'ወደ ስራዎች ተመለስ',
    backToJob: 'ወደ ስራ ተመለስ',
    kmAwayFromLocation: 'ኪ.ሜ ርቀት ከእርስዎ ቦታ',
    employerRating: 'የአሰሪ ደረጃ:',
    postedBy: 'የለጠፈው:',
    alreadyAppliedStatus: 'አስቀድመው አመልክተዋል — ሁኔታ:',
    viewLocation: 'ቦታ ይመልከቱ —',
    viewJobAddress: 'የስራ አድራሻ ይመልከቱ',
    generateCV: 'ሲቪ ያመንጩ',
    generatingYourCV: 'ሲቪዎን በማመንጨት ላይ...',
    downloadCV: 'ሲቪ ያውርዱ',
    sendCVWithApplication: 'ሲቪ ከማመልከቻ ጋር ይላኩ',
    applyThroughSira: 'በሲራ ያመልክቱ',
    quickApply: 'ፈጣን ማመልከቻ',
    messageEmployer: 'ለአሰሪ መልእክት ይላኩ',
    voiceApplication: 'የድምፅ ማመልከቻ',
    speakYourApplicationDesc: 'ማመልከቻዎን ይናገሩ እና የመነጨውን ጽሁፍ ያስተካክሉ',
    manualForm: 'የእጅ ቅጽ',
    fillManuallyDesc: 'የማመልከቻ ዝርዝሮችዎን በእጅ ይሙሉ',
    listeningTapToStop: 'በማዳመጥ ላይ... ለማቆም ይንኩ',
    processing: 'በማቀነባበር ላይ...',
    tapToSpeakApplication: 'ማመልከቻዎን ለመናገር ይንኩ',
    generatedApplicationText: 'የተፈጠረ የማመልከቻ ጽሁፍ',
    spokenAppPlaceholder: 'የተናገሩት ማመልከቻ እዚህ ይታያል። በነፃ ማስተካከል ይችላሉ...',
    editToCorrect: 'ስህተቶችን ለማስተካከል ወይም መልእክትዎን ለማሻሻል ከላይ ያለውን ጽሁፍ ያርትዑ',
    attachCVWithApplication: 'ሲቪ ከማመልከቻ ጋር ያያይዙ',
    apply: 'ያመልክቱ',
    coverMessage: 'ሽፋን መልእክት',
    writeMessagePlaceholder: 'የማመልከቻ መልእክትዎን እዚህ ይጻፉ...',
    experienceYears: 'ልምድ (ዓመታት)',
    experiencePlaceholder: 'ለምሳሌ 3',
    availability: 'መገኘት',
    immediate: 'ወዲያውኑ',
    withinWeek: 'በሳምንት ውስጥ',
    withinMonth: 'በወር ውስጥ',
    skillsPlaceholder: 'ለምሳሌ ቧንቧ ስራ፣ ኤሌክትሪክ፣ አናጢነት',
    applicationSubmitted: 'ማመልከቻ ቀርቧል!',
    yourApplicationFor: 'ለሚከተለው ስራ ያቀረቡት ማመልከቻ',
    hasBeenSent: 'ተልኳል',
    redirectingToJobDetails: 'ወደ ስራ ዝርዝሮች እያዞረ ነው...',
    yrsExp: 'ዓመታት ልምድ',

    voiceAssistantSubtitle: 'በአማርኛ፣ በአፋን ኦሮሞ ወይም በእንግሊዝኛ ይናገሩ። ሥራ እርምጃ ከመውሰዱ በፊት የሰማውን ማስተካከል ይችላሉ።',
    processingVoice: 'ሥራ በማሰብ ላይ ነው…',
    autoStopHint: 'ከ~10 ሰከንድ በኋላ በራሱ ይቆማል።',
    transcribedTextLabel: 'የተቀዳ ጽሑፍ (ሊስተካከል የሚችል)',
    suggestedJobsLabel: 'የቀረቡ ሥራዎች',

    typeFallbackPlaceholder: 'ትዕዛዝ ወይም የስራ መደብ እዚህ ይጻፉ…',
    saveLabel: 'ለውጦችን አስቀምጥ',
    cancelLabel: 'ሰርዝ',

    users: 'ተጠቃሚዎች',

    landingHeroTitle: 'ሲራ-ቮይስ: ለእለታዊ ሰራተኞች AI ወኪል',
    landingHeroSubtitle: 'ክህሎትዎን ይናገሩ፣ ተቀጥሩ፣ እና ሲራ-ቮይስ ማጣመሪያውን ያድርግ። አማርኛ፣ አፋን ኦሮሞ፣ እንግሊዘኛ—ድምጽዎ የሲቪዎ ነው።',
    landingWorkerCta: 'ሰራተኛ ነኝ →',
    landingWorkerSub: 'ወደ ድምጽ መገለጫ ይሂዱ',
    landingEmployerCta: 'አሰሪ ነኝ →',
    landingEmployerSub: 'ስራ ለጥፍ',
    landingVoiceTag: 'ድምጽ → AI → የስራ ማጣመር',
    landingAboutSection: 'ትልቁ ለውጥ 🧠',
    landingAboutTitle: 'ዝም ብለው ይናገሩ ሲራ ያገኛል፣ ያመለክታል እና ስራዎችን ያስተዳድራል።',
    landingAgencyImpact: 'የኤጀንሲ ደረጃ ተፅዕኖ',
    landingBeforeEffort: 'ከዚህ በፊት፡ የእጅ ስራ',
    landingBeforeDesc: 'ተጠቃሚዎች ስራዎችን ፈልገው በእጃቸው ያመለክታሉ። በጣም ብዙ መሰናክል።',
    landingNowAgency: 'አሁን: AI ኤጀንሲ',
    landingNowDesc: 'ተጠቃሚው ይናገራል። AI ወኪል ሁሉንም ነገር ያደርጋል—መገለጫ ይፈጥራል፣ ተዛማጆችን ያገኛል፣ እና በራሱ ያመለክታል።',
    landingHeroBadge: 'የእርስዎ AI የስራ ወኪል',
    landingVoiceAIMatch: 'የድምጽ AI ማዛመጃ',
    landingNearbyJobsFound: '12 በአቅራቢያ ያሉ ስራዎች ተገኝተዋል',
    landingFooterCopyright: '© 2026 ሲራ-ቮይስ — ስራን በAI ወኪል ኤጀንሲ እንደገና መወሰን',
    landingAiAgent: 'AI የስራ ወኪል',
    landingAiAgentDesc: 'ይህ የስራ ቦርድ አይደለም; የግል ረዳት ነው። እርስዎ እያኙ ስራዎችን ይከታተላል እና ያመለክታል።',
    landingLocalLang: 'የአካባቢ ቋንቋ ችሎታ',
    landingLocalLangDesc: 'ለኢትዮጵያ የተሰራ። በአማርኛ፣ በአፋን ኦሮሞ ወይም በእንግሊዘኛ ይናገሩ። ሲራ ክህሎትዎን በትክክል ይረዳል።',
    landingHowItWorks: 'ደረጃ በደረጃ 🛠️',
    landingHowItWorksTitle: 'ድምጽዎ ሲቪዎ ይሆናል',
    landingStep1Title: 'ክህሎቶችን ይናገሩ',
    landingStep1Desc: 'በተፈጥሮ ይናገሩ። AI ክህሎቶችዎን፣ ልምድዎን እና ተመራጭ ቦታዎችዎን በቀጥታ ከድምጽዎ ያወጣል።',
    landingStep2Title: 'AI ያዛምዳል',
    landingStep2Desc: 'የጌሚኒ ወኪል ስለ ስራ ማስታወቂያዎች ያስባል እና ለተሻሉ ዕድሎች ወዲያውኑ ማሳወቂያ ይልካል።',
    landingStep3Title: 'ይረጋገጡ',
    landingStep3Desc: 'ጂፒኤስ መከታተያ አስተማማኝ ስራን ያረጋግጣል፣ እና የማጠናቀቂያ ፎቶዎች ተግባሮችዎ መከናወናቸውን ያረጋግጣሉ።',
    landingEmployerTitle: 'ብልህ የአሰሪ ወኪል',
    landingEmployerHeading: 'ጥራት ያለው ተሰፍ ይቅጠሩ፣ ያለምንም ጥረት።',
    landingVoicePosting: '🎙️ የድምጽ ስራ ልጥፍ',
    landingVoicePostingDesc: 'ፍላጎቶችዎን ይናገሩ፤ AI የስራ ልጥፉን ያዋቅራል እና በራሱ ይከፋፍላል።',
    landingOneClickHiring: '⚡ ባለአንድ ጠቅታ ቅጥር',
    landingOneClickHiringDesc: 'በክህሎት እና በርቀት ላይ የተመሰረቱ በAI የተመደቡ እጩዎችን ይገምግሙ። በአንድ ንክኪ ይቅጠሩ።',
    landingWorkerSection: 'ለሰራተኞች የተሰራ',
    landingWorkerHeading: 'ዲጂታል የድምጽ ሲቪዎን ይገንቡ እና ተቀጥሩ',
    landingWorkerStep1: '1. ድምጽ-መጀመሪያ የሲቪ ፍጠረት',
    landingWorkerStep1Desc: 'ክህሎቶችዎን በመናገር ሙሉ መገለጫ ይፍጠሩ።',
    landingWorkerStep2: '2. የአካባቢ እድሎችን ያግኙ',
    landingWorkerStep2Desc: 'በአቅራቢያ ያሉ የተረጋገጡ ስራዎችን ያግኙ። የእኛ AI ወኪል ከተሻሉ አማራጮች ጋር ያዛምድዎታል።',
    landingWorkerStep3: '3. በፍጥነት ተቀጥሩ እና ይክፈሉ',
    landingWorkerStep3Desc: 'ማመልከቻዎችን ይከታተሉ፣ ቀጥተኛ ቅናሾችን ያግኙ እና አስተማማኝ የክፍያ ማረጋገጫ ያግኙ።',
    landingWorkerBtn: 'የድምጽ መገለጫዎን አሁን ይፍጠሩ',
    landingFooterDesc: 'የስራ መተግበሪያ አልገነባንም። ለመደበኛ ያልሆነ የሰው ኃይል የሚሰራ AI ወኪል ገንብተናል።',
    landingFooterPlatform: 'መድረክ',
    landingFooterJoinWorker: 'እንደ ሰራተኛ ይቀላቀሉ',
    landingFooterJoinEmployer: 'እንደ አሰሪ ይቀላቀሉ',
    landingFooterHowItWorks: 'እንዴት እንደሚሰራ',
    landingFooterConnect: 'ያገናኙ',
    landingFooterLocation: 'አዲስ አበባ, ኢትዮጵያ',
  },
  or: {
    label: 'Afaan Oromoo 🇪🇹',
    magicLine: 'Dubbadhu qofa — Siiraan hojii barbaadi, galmaa’i, fi bulchi.',
    micPlaceholder: 'Dandeettii, muuxannoo, fi bakka kee dubbadhu…',
    headerSearchPlaceholder: 'Hojii sagalee ykn barreeffamaan barbaadi…',
    mapApplyCta: 'Galmaa’uuf dubbadhu',
    ratingsTitle: 'Sadarkaa & Yaada',
    ratingsSubtitle: 'Hojii xumurame irratti sadarkaa kenni; amanamummaa ijaar.',
    rateButton: 'Sadarkaa Kenni',
    voiceRatingTitle: 'Yaada Sagalee',
    voiceRatingSubtitle: 'Yaada kee dubbadhu, booda barruu sirreessi.',
    close: 'Cufi',
    cancel: 'Dhiisi',
    submitRating: 'Sadarkaa Ergi',
    tapToSpeak: 'Dubbachuuf tuqi',
    listening: 'Dhaggeeffachaa jira… amma dubbadhu',
    transcribing: 'Barreessaa…',
    feedbackLabel: 'Yaada',
    speakLabel: 'Dubbadhu',
    jobPostTitle: 'Hojii Maxxansi',
    jobPostSubtitle: 'Hojii sagalee-duraa: yeroo tokko ibsi, Siiraan guutuu foormii guuti.',
    voiceModeLabel: 'Haala Sagalee',
    voiceModeHint: 'Dubbadhu: hojii/gahee, bakka, mindaa, guyyaa/sa’aatii.',
    voiceModeTap: 'Hojii ibsuuf makiroofiin tuqi',
    voiceModeExample: 'Fakkeenya: “Bore Booletti qulqullinaa 2 barbaada, 500 birrii.”',
    fieldTitle: 'Mata-duree',
    fieldCategory: 'Gosa',
    fieldLocation: 'Bakka',
    fieldSalary: 'Mindaa (ETB)',
    fieldDescription: 'Ibsa',
    dashboard: 'Daashboordii',
    availableJobs: 'Hojii Jiran',
    talkToSira: 'Siraa wajjin dubbadhu',
    voiceToCV: 'Sagalee CV Irratti',
    jobMap: 'Kaartaa Hojii',
    history: 'Seenaa',
    ratings: 'Sadarkaa',
    profile: 'Profayilii',
    employerDashboard: 'Daashboordii Hojjeesisaa',
    employerSub: 'Walitti hidhiinsa bilchaataa. Waliigaltee amansiisaa. Kaffaltii siriitti deemuf.',
    postNewJob: 'Hojii Haaraa Baasi',
    yourOpenings: 'Banakkaawwan Hojii Keessan',
    aiMatchmaking: 'Walitti Hidhiinsa AI',
    topCandidates: 'Iyyattoota dursa qaban kan pirojektii filatameef',
    noAppsFoundJob: 'Hojii kanaaf iyyannoon argame hin jiru',
    applicants: 'Galmaa’ota',
    adminDashboard: 'Daashboordii Bulchaa',
    scamLog: 'Galmee Madaa’aa',
    systemLanguage: 'Afaan Sirnaa',
    login: 'Seeni',
    register: 'Galmaa’i',
    logout: 'Ba’i',
    search: 'Barbaadi',
    notifications: 'Beeksisa',
    settings: 'Qindaa’i',

    welcomeBack: 'Baga nagaan dhuftan!',
    aiMatchingActive: 'Walitti Hidhiinsa AI Hojii Irra Jira',
    voiceHuntingJobs: 'Eejantiin sagalee keessanii naannoo keessanitti hojii barbaadaa jira.',
    clickVoiceSira: 'Sagalee Siiraa fayyadamuuf tuqi',
    talkToFindJobs: 'Hojii argachuuf dubbadhu',
    weeklyEarnings: 'Galii Torbee',
    calculatedSoon: 'Dhiheenyatti herregama',
    workerRating: 'Sadarkaa Hojjetaa',
    completedJobsCount: 'Hojiiwwan xumuraman',
    activeApplications: 'Iyyannoo Hojii Hojjatamaa Jiru',
    liveFromHistory: 'Seenaa irraa kallattiin',
    bestMatchesForYou: 'Madaallii Gaarii Siif Ta’an',
    viewAll: 'Hunda Ilaali',
    noMatchesYet: 'Hanga ammaatti madaalliin argame hin jiru.',
    voiceSearchMapHint: 'Barbaacha sagalee yaali ykn hojiiwwan qorachuuf kaartaa banadhu.',
    generateVoiceCv: 'Voice-CV Tolchi',
    voiceCvSubtitle: 'Sira-AI waraabbii sekondi 30 irraa profaayila ogummaa kee akka ijaaru heeymamiif.',
    startNow: 'Amma Jalqabi',
    nearbyJobs: 'Hojiiwwan Dhihoo',
    openJobMap: 'Kaartaa Hojii Bani',
    exploreJobs: 'Hojiiwwan Sakatta’i',
    detailsArrow: 'Ibsa Guutuu →',
    speakThreeLanguagesHint: "Afaan Oromoo, Amharic, ykn English dubbadhu. Tarkaanfii fudhachuu dura waan Siiraan dhaga'e sirreessuu dandeessa.",
    tapToSpeakHint: 'Dubbachuuf tuqi. Sekondii ~10 booda ofiin dhaabbata.',
    transcribedTextEditable: 'Barreeffama waraabbame (gulaalamuu kan danda’u)',
    voiceBecomesCvTitle: 'Sagaleen kee CV kee ta’a',
    voiceFirstCapture: 'Waraabbii Sagalee Jalqabaa',
    tapMicAndSpeak: 'Maayikii tuquun dubbadhu',
    whatSiraHeard: 'Waan Siiraan Dhaga’e',
    extractedSkills: 'Ogummaa Baafame',
    speakExampleHint1: 'Fakkeenyaaf dubbachuuu dandeessa: “Ani hojjetaa dhaanbaa (plumber) muuxannoo waggaa 3 qabu Megenaanyatti.”',
    speakExampleHint2: '“እኔ የቤት ሰራተኛ ነኝ፣ ቦሌ እኖራለሁ…”',
    applicationHistoryTitle: 'Seenaa Iyyannoo',
    trackHistorySubtitle: 'Iyyannoo, qaxarrii fi xumura hunda bakka tokkotti hordofi.',
    noApplicationsYet: 'Hanga ammaatti iyyannoon hin jiru.',
    walletAndEarningsTitle: 'Waletii & Galii Keessan',
    walletSubtitle: 'Eeybama keessan, seenaa baasii hordofaa fi gara baankiitti kaffaltiin akka darbu gaafadha.',
    withdrawFunds: 'Maallaqa Baasi',
    availableBalance: 'Haftee Maallaqa Jiru',
    readyForImmediateWithdrawal: 'Battalatti baasuuf kan qophaaye',
    totalLifetimeEarned: 'Waliigala Maallaqa Argame',
    fromJobAllocations: 'Hojiiwwan xumuraman irraa',
    inTransferProcessing: 'Adeemsa Dabarsaa Irratti Kan Jiru',
    cashoutEventsAwaiting: 'Adeemsa baasii maallaqa eeggachaa jiru',
    statementLedger: 'Galmee Giddugaleessa daldalaa',
    noTransactionsLogged: 'Akkaawuntii kana irratti hanga ammaatti daldalli galmeeffame hin jiru.',
    failedToLoadTransactions: 'Seenaa daldalaa fiduun hin danda’amne',
    bioLabel: 'Waa’ee Koo',
    skillsLabel: 'Ogummaawwan',
    noSkillsAdded: 'Ogummaan dabalame hin jiru.',
    experienceLabel: 'Muuxannoo Hojii',
    yearsExperience: 'Waggaa muuxannoo hojii',
    preferredLanguageLabel: 'Afaan Filatame',
    aiAgentPreferences: 'Filannoo Eejansii AI',
    autoMatchingAndOneClick: 'Madaallii of-gutoof kaffaltii qofaan iyyachuu',
    autoApplyLabel: 'Ofiin Iyyadhu (Auto-Apply)',
    noJobSelected: 'Hojiin filatame hin jiru',
    scanningDatabase: 'Kuusaa daataa sakatta’aa jira...',
    aiRecommendedMatch: 'AIn Kan Mirkanae',
    verifiedBadge: 'Mirkanaa’e',
    kmAway: 'KM fagaa',
    matchPercentage: 'Madaalawaa',
    hiringProgress: 'Qaxaraa jira...',
    hireAction: 'Qaxari',
    backToJobs: 'Gara Hojiiwwan Deebi\'i',
    backToJob: 'Gara Hojii Deebi\'i',
    kmAwayFromLocation: 'KM fageenya bakka kee irraa',
    employerRating: 'Sadarkaa Hojjeessisaa:',
    postedBy: 'Kan baase:',
    alreadyAppliedStatus: 'Duraan galmaaheera — Haala:',
    viewLocation: 'Bakka Ilaali —',
    viewJobAddress: 'Teessoo Hojii Ilaali',
    generateCV: 'CV Uumi',
    generatingYourCV: 'CV kee uumaa jira...',
    downloadCV: 'CV Buufadhu',
    sendCVWithApplication: 'CV Iyyannoo wajjin ergi',
    applyThroughSira: 'Siraan Galmaa\'i',
    quickApply: 'Ariitiin Galmaa\'i',
    messageEmployer: 'Hojjeessisaaf Ergaa Ergi',
    voiceApplication: 'Iyyannoo Sagalee',
    speakYourApplicationDesc: 'Iyyannoo kee dubbadhu fi barreeffama uumame sirreessi',
    manualForm: 'Foormii Harkaa',
    fillManuallyDesc: 'Ibsa iyyannoo kee harkaan guuti',
    listeningTapToStop: 'Dhaggeeffachaa... Dhaabuuf tuqi',
    processing: 'Adeemsifamaa jira...',
    tapToSpeakApplication: 'Iyyannoo kee dubbachuuf tuqi',
    generatedApplicationText: 'Barreeffama Iyyannoo Kan Uumame',
    spokenAppPlaceholder: 'Iyyannoo dubbatte kee asitti mul\'ata. Ofumaan sirreessuu dandeessa...',
    editToCorrect: 'Dogoggora sirreessuuf ykn ergaa kee fooyyessuuf barreeffama olii gulaali',
    attachCVWithApplication: 'CV Iyyannoo wajjin olka\'i',
    apply: 'Galmaa\'i',
    coverMessage: 'Ergaa Haguugaa',
    writeMessagePlaceholder: 'Ergaa iyyannoo kee asitti barreessi...',
    experienceYears: 'Muuxannoo (waggaa)',
    experiencePlaceholder: 'Fkn 3',
    availability: 'Argamuu',
    immediate: 'Ariitiin',
    withinWeek: 'Torbe keessa',
    withinMonth: 'Ji\'a keessa',
    skillsPlaceholder: 'Fkn: Dhaanbaa, Elektirikii, Muka-Saqqii',
    applicationSubmitted: 'Iyyannoo Dhiyaate!',
    yourApplicationFor: 'Iyyannoo kee hojii',
    hasBeenSent: 'ergameera',
    redirectingToJobDetails: 'Gara ibsa hojiiitti deebi\'aa jira...',
    yrsExp: 'waggaa muuxannoo',

    voiceAssistantSubtitle: "Afaan Oromoo, Amaariffa ykn Ingiliffaan dubbadhu. Sira'n gocha dura waan dhaga'e sirreessuu dandeessa.",
    processingVoice: "Sira'n yaadaa jira…",
    autoStopHint: 'Sekondii ~10 booda ofiin dhaabbata.',
    transcribedTextLabel: 'Barreeffama waraabame (kan sirreeffamu)',
    suggestedJobsLabel: 'Hojiiwwan siif dhiyaatan',

    typeFallbackPlaceholder: 'Ajaja ykn gosa hojii barreessi…',
    saveLabel: 'Hanga jidduu ol-kaahi',
    cancelLabel: 'Haqi',

    landingHeroTitle: 'Sira-Voice: Eejjantii AI Hojjettoota Guyyaa Guyyaatiif',
    landingHeroSubtitle: 'Dandeettii kee dubbadhu, qaxarami, Sira-Voiceen madaallii sirreessi. Afaan Oromoo, Amaariffa, Ingiliffa—sagaleen kee CV kee ti.',
    landingWorkerCta: 'Hojjetaan →',
    landingWorkerSub: 'Gara Sagalee Profayilii',
    landingEmployerCta: 'Qaxartaan →',
    landingEmployerSub: 'Hojii Baasi',
    landingVoiceTag: 'Sagalee → AI → Madaallii Hojii',
    users: 'Fayyadamtoota',

    navAbout: 'Waa\'ee',
    navHowItWorks: 'Akkamitti Hojjata',
    navEmployers: 'Qaxartoota',
    navWorkers: 'Hojjettoota',
    navContact: 'Nu Qunnami',

    landingAboutSection: 'Jijjiirama Guddaa 🧠',
    landingAboutTitle: 'Dubbadhu — Siiraan hojii barbaada, iyyatti, fi bulchi.',
    landingAgencyImpact: 'Dhiibbaa Sadarkaa Ejensii',
    landingBeforeEffort: 'Dur: Hojii Harkaa',
    landingBeforeDesc: 'Fayyadamonni hojii barbaadani harkaan iyyatu. Baay\'ee rakkoo qaba.',
    landingNowAgency: 'Amma: AI Ejensii',
    landingNowDesc: 'Fayyadamaan dubbata. Eejjantiin AI HUNDAA hojjata—profayilii ijaara, madaallii argata, ofiin iyyata.',
    landingHeroBadge: 'Eejjantii Hojii AI Keessan',
    landingVoiceAIMatch: 'Madaallii Sagalee AI',
    landingNearbyJobsFound: 'Hojiiwwan Dhihoo 12 Argan',
    landingFooterCopyright: '© 2026 SIRA-VOICE — Ejensii AI\'n Hojii Haaraa',
    landingAiAgent: 'Eejjantii Hojii AI',
    landingAiAgentDesc: 'Baaddii hojii miti; gargaaraa dhuunfaati. Hojii hordofee siif iyyata ati raftuu.',
    landingLocalLang: 'Dandeettii Afaan Naannoo',
    landingLocalLangDesc: 'Itoophiyaaf kan ijaarame. Afaan Oromoo, Amaariffa ykn Ingiliffaan dubbadhu. Siirri dandeettii kee sirritti hubatti.',
    landingHowItWorks: 'Tarba-tarbaan 🛠️',
    landingHowItWorksTitle: 'Sagaleen kee CV kee ta\'a',
    landingStep1Title: 'Dandeettii Dubbadhu',
    landingStep1Desc: "Uumamaan dubbadhu. AI'n dandeettii, muuxannoo fi bakka filatamu kee kallattiin sagalee kee irraa baasa.",
    landingStep2Title: "AI'n Madaala",
    landingStep2Desc: 'Eejjantiin Gemini maxxansa hojii irratti yaadaafi beeksisa battalamaa madaalii gaariif erga.',
    landingStep3Title: 'Mirkanaa\'i',
    landingStep3Desc: 'GPS hordoffii hojiin amanamaa ta\'uu mirkaneessa, suuraan xumuraa hojiiwwan kee raawwatamuu isaanii mirkaneessa.',
    landingEmployerTitle: 'Eejjantii Qaxartaa Caalmaataa',
    landingEmployerHeading: 'Hojjetaa Qulqullaa\'aa Qaxari, Rakkoo Malee.',
    landingVoicePosting: '🎙️ Maxxansa Hojii Sagaleedhaan',
    landingVoicePostingDesc: 'Barbaachisummaa kee dubbadhu; AI maxxansa hojii ijaaree ofiin ramada.',
    landingOneClickHiring: '⚡ Qaxarrii Tigiltii Tokkotti',
    landingOneClickHiringDesc: 'Dandeetti fi fageenyatti bu\'uureffamee qaxartota AIn filatame sakatta\'i. Tigiltii tokkoon qaxari.',
    landingWorkerSection: 'Hojjettootaaf ijaarame',
    landingWorkerHeading: 'CV Sagalee Digitaalaa Keesson Ijaari fi Qaxarami',
    landingWorkerStep1: '1. Ijaarsa CV Sagalee-Duraa',
    landingWorkerStep1Desc: 'Dandeettii kee dubbachuun profayilii guutuu ijaari.',
    landingWorkerStep2: '2. Carraa Naannoo Barbaadi',
    landingWorkerStep2Desc: 'Hojii mirkanaa\'e dhihoo argadhu. Eejjantiin AI keenya madaalii filatamaan si madaala.',
    landingWorkerStep3: '3. Ariitii Qaxarami fi Kafalamu',
    landingWorkerStep3Desc: 'Iyyannoo hordofi, dhiyeeffata kallattiin argadhu, fi mirkaneessa kaffaltii amanamaa argadhu.',
    landingWorkerBtn: 'Profayilii Sagalee kee Amma Ijaari',
    landingFooterDesc: 'Appii hojii hin ijaarin. Eejjantii AI hojii humna idilee hin taaneef hojjattu ijaarree jira.',
    landingFooterPlatform: 'Maddii',
    landingFooterJoinWorker: 'Hojjetaa ta\'i',
    landingFooterJoinEmployer: 'Qaxartaa ta\'i',
    landingFooterHowItWorks: 'Akkamitti hojjata',
    landingFooterConnect: 'Walitti Hidhami',
    landingFooterLocation: 'Finfinnee, Itoophiyaa',
  },
  en: {
    label: 'English 🇬🇧',
    magicLine: 'Just speak — Sira finds, applies, and manages jobs for you.',
    micPlaceholder: 'Speak your skill, experience, and location…',
    headerSearchPlaceholder: 'Search jobs by voice or text…',
    mapApplyCta: 'Just Speak to Apply',
    ratingsTitle: 'Ratings & Feedback',
    ratingsSubtitle: 'Rate completed jobs to build trust and verified badges.',
    rateButton: 'Rate',
    voiceRatingTitle: 'Voice Rating',
    voiceRatingSubtitle: 'Speak your feedback, then adjust text if needed.',
    close: 'Close',
    cancel: 'Cancel',
    submitRating: 'Submit Rating',
    tapToSpeak: 'Tap to speak',
    listening: 'Listening… speak now',
    transcribing: 'Transcribing…',
    feedbackLabel: 'Feedback',
    speakLabel: 'Speak',
    jobPostTitle: 'Post a Job',
    jobPostSubtitle: 'Voice-first job posting: describe it once, Sira fills the form.',
    voiceModeLabel: 'Voice Mode',
    voiceModeHint: 'Speak: role, location, pay, date/time.',
    voiceModeTap: 'Tap mic to describe the job',
    voiceModeExample: 'Example: “Need 2 cleaners tomorrow in Bole, 500 birr.”',
    fieldTitle: 'Title',
    fieldCategory: 'Category',
    fieldLocation: 'Location',
    fieldSalary: 'Salary (ETB)',
    fieldDescription: 'Description',
    dashboard: 'Dashboard',
    availableJobs: 'Available Jobs',
    talkToSira: 'Talk to Sira',
    voiceToCV: 'Voice to CV',
    jobMap: 'Job Map',
    history: 'History',
    ratings: 'Ratings',
    profile: 'Profile',
    employerDashboard: 'Employer Dashboard',
    employerSub: 'Smart matching. Secure contracts. Seamless payments.',
    postNewJob: 'Post New Job',
    yourOpenings: 'Your Openings',
    aiMatchmaking: 'AI Matchmaking',
    topCandidates: 'Top candidates for selected project',
    noAppsFoundJob: 'No applications found for this job',
    applicants: 'Applicants',
    adminDashboard: 'Admin Dashboard',
    scamLog: 'Scam Log',
    systemLanguage: 'System Language',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    search: 'Search',
    notifications: 'Notifications',
    settings: 'Settings',

    welcomeBack: 'Welcome back!',
    aiMatchingActive: 'AI Matching Active',
    voiceHuntingJobs: 'Your voice agent is hunting for jobs near you.',
    clickVoiceSira: 'Click to use Sira Voice',
    talkToFindJobs: 'Talk to find jobs',
    weeklyEarnings: 'Weekly Earnings',
    calculatedSoon: 'Calculated soon',
    workerRating: 'Worker Rating',
    completedJobsCount: 'completed jobs',
    activeApplications: 'Active Applications',
    liveFromHistory: 'Live from history',
    bestMatchesForYou: 'Best Matches For You',
    viewAll: 'View All',
    noMatchesYet: 'No matches yet.',
    voiceSearchMapHint: 'Try voice search or open the map to explore jobs.',
    generateVoiceCv: 'Generate Voice-CV',
    voiceCvSubtitle: 'Let Sira-AI build your professional profile from a 30-second recording.',
    startNow: 'Start Now',
    nearbyJobs: 'Nearby Jobs',
    openJobMap: 'Open Job Map',
    exploreJobs: 'Explore Jobs',
    detailsArrow: 'Details →',
    speakThreeLanguagesHint: 'Speak in Amharic, Afaan Oromo, or English. You can edit what Sira heard before taking action.',
    tapToSpeakHint: 'Tap to speak. Auto-stops after ~10 seconds.',
    transcribedTextEditable: 'Transcribed text (editable)',
    voiceBecomesCvTitle: 'Your Voice becomes your CV',
    voiceFirstCapture: 'Voice‑First Capture',
    tapMicAndSpeak: 'Tap the mic and speak',
    whatSiraHeard: 'What Sira heard',
    extractedSkills: 'Extracted Skills',
    speakExampleHint1: 'Speak something like: “I am a plumber with 3 years experience in Megenagna.”',
    speakExampleHint2: '“እኔ የቤት ሰራተኛ ነኝ፣ ቦሌ እኖራለሁ…”',
    applicationHistoryTitle: 'Application History',
    trackHistorySubtitle: 'Track every application, hire, and completion in one place.',
    noApplicationsYet: 'No applications yet.',
    walletAndEarningsTitle: 'Your Wallet & Earnings',
    walletSubtitle: 'Track your balance, statement history, and request bank disbursements.',
    withdrawFunds: 'Withdraw Funds',
    availableBalance: 'Available Balance',
    readyForImmediateWithdrawal: 'Ready for immediate withdrawal',
    totalLifetimeEarned: 'Total Lifetime Earned',
    fromJobAllocations: 'From completed job allocations',
    inTransferProcessing: 'In Transfer Processing',
    cashoutEventsAwaiting: 'cashout events awaiting transit',
    statementLedger: 'Statement Transaction Ledger',
    noTransactionsLogged: 'No transactions logged on this account yet.',
    failedToLoadTransactions: 'Failed to load transaction history',
    bioLabel: 'Bio',
    skillsLabel: 'Skills',
    noSkillsAdded: 'No skills added.',
    experienceLabel: 'Experience',
    yearsExperience: 'years experience',
    preferredLanguageLabel: 'Preferred Language',
    aiAgentPreferences: 'AI Agent Preferences',
    autoMatchingAndOneClick: 'Auto-matching and one-click applications',
    autoApplyLabel: 'Auto-Apply',
    noJobSelected: 'No job selected',
    scanningDatabase: 'Scanning database...',
    aiRecommendedMatch: 'AI Recommended Match',
    verifiedBadge: 'Verified',
    kmAway: 'KM away',
    matchPercentage: 'Match',
    hiringProgress: 'Hiring...',
    hireAction: 'Hire',
    backToJobs: 'Back to Jobs',
    backToJob: 'Back to Job',
    kmAwayFromLocation: 'km away from your location',
    employerRating: 'Employer Rating:',
    postedBy: 'Posted by:',
    alreadyAppliedStatus: 'Already applied — Status:',
    viewLocation: 'View Location —',
    viewJobAddress: 'View Job Address',
    generateCV: 'Generate CV',
    generatingYourCV: 'Generating your CV...',
    downloadCV: 'Download CV',
    sendCVWithApplication: 'Send CV with application',
    applyThroughSira: 'Apply Through Sira',
    quickApply: 'Quick Apply',
    messageEmployer: 'Message Employer',
    voiceApplication: 'Voice Application',
    speakYourApplicationDesc: 'Speak your application and edit the generated text',
    manualForm: 'Manual Form',
    fillManuallyDesc: 'Fill in your application details manually',
    listeningTapToStop: 'Listening... Tap to stop',
    processing: 'Processing...',
    tapToSpeakApplication: 'Tap to speak your application',
    generatedApplicationText: 'Generated Application Text',
    spokenAppPlaceholder: 'Your spoken application will appear here. You can edit it freely...',
    editToCorrect: 'Edit the text above to correct mistakes or improve your message',
    attachCVWithApplication: 'Attach CV with application',
    apply: 'Apply',
    coverMessage: 'Cover Message',
    writeMessagePlaceholder: 'Write your application message here...',
    experienceYears: 'Experience (years)',
    experiencePlaceholder: 'e.g. 3',
    availability: 'Availability',
    immediate: 'Immediate',
    withinWeek: 'Within a week',
    withinMonth: 'Within a month',
    skillsPlaceholder: 'e.g. Plumbing, Electrical, Carpentry',
    applicationSubmitted: 'Application Submitted!',
    yourApplicationFor: 'Your application for',
    hasBeenSent: 'has been sent.',
    redirectingToJobDetails: 'Redirecting to job details...',
    yrsExp: 'yrs exp',

    voiceAssistantSubtitle: 'Speak in Amharic, Afaan Oromo, or English. You can edit what Sira heard before taking action.',
    processingVoice: 'Sira is thinking…',
    autoStopHint: 'Auto-stops after ~10 seconds.',
    transcribedTextLabel: 'Transcribed text (editable)',
    suggestedJobsLabel: 'Suggested jobs',

    typeFallbackPlaceholder: 'Type command or job title manually...',
    saveLabel: 'Save Changes',
    cancelLabel: 'Cancel',

    users: 'Users',

    navAbout: 'About',
    navHowItWorks: 'How it Works',
    navEmployers: 'Employers',
    navWorkers: 'Workers',
    navContact: 'Contact Us',

    landingHeroTitle: 'Sira-Voice: The AI Agent for Everyday Workers',
    landingHeroSubtitle: 'Speak your skills, get hired, and let Sira-Voice handle the matching. Amharic, Afan Oromo, English—your voice is your CV.',
    landingWorkerCta: 'I\'m a Worker →',
    landingWorkerSub: 'Go to Voice Profile',
    landingEmployerCta: 'I\'m an Employer →',
    landingEmployerSub: 'Post a Job',
    landingVoiceTag: 'Voice → AI → Job Match',
    landingAboutSection: 'The Big Shift',
    landingAboutTitle: 'Just speak — Sira finds, applies, and manages jobs for you.',
    landingAgencyImpact: 'Agency-Level Impact',
    landingBeforeEffort: 'Before: Manual Effort',
    landingBeforeDesc: 'Users search jobs and apply manually. Too much friction.',
    landingNowAgency: 'Now: AI Agency',
    landingNowDesc: 'User speaks. AI Agent does EVERYTHING—creates profile, finds matches, and applies automatically.',
    landingHeroBadge: 'Your AI Job Agent',
    landingVoiceAIMatch: 'Voice AI Match',
    landingNearbyJobsFound: '12 Nearby Jobs Found',
    landingFooterCopyright: '© 2026 SIRA-VOICE — Redefining Work with AI Agent Agency',
    landingAiAgent: 'AI Job Agent',
    landingAiAgentDesc: 'It\'s not a job board; it\'s a personal assistant. It monitors jobs and applies for you while you sleep.',
    landingLocalLang: 'Local Language Mastery',
    landingLocalLangDesc: 'Built for Ethiopia. Speak in Amharic, Afan Oromo, or English. Sira understands your skills perfectly.',
    landingHowItWorks: 'Step-by-Step',
    landingHowItWorksTitle: 'Your Voice Becomes Your CV',
    landingStep1Title: 'Speak Skills',
    landingStep1Desc: 'Just speak naturally. AI extracts your skills, experience, and preferred locations directly from your voice.',
    landingStep2Title: 'AI Matches',
    landingStep2Desc: 'The Gemini Agent reasons about job postings and sends push notifications for the best fits instantly.',
    landingStep3Title: 'Get Verified',
    landingStep3Desc: 'GPS tracking ensures trustworthy work, and proof-of-completion photos confirm your tasks are done.',
    landingEmployerTitle: 'Smart Employer Agent',
    landingEmployerHeading: 'Hire Quality Talent, Effortlessly.',
    landingVoicePosting: 'Voice Job Posting',
    landingVoicePostingDesc: 'Speak your requirements; AI structures the job post and categorizes it automatically.',
    landingOneClickHiring: '1-Click Hiring',
    landingOneClickHiringDesc: 'Review AI-ranked candidates based on skill and distance. Hire instantly with one tap.',
    landingWorkerSection: 'Built for Workers',
    landingWorkerHeading: 'Build Your Digital Voice CV & Get Hired',
    landingWorkerStep1: '1. Voice-First CV Creation',
    landingWorkerStep1Desc: 'Create a full profile by speaking your skills.',
    landingWorkerStep2: '2. Find Local Opportunities',
    landingWorkerStep2Desc: 'Discover nearby, verified jobs. Our AI Agent matches you with the best fits instantly.',
    landingWorkerStep3: '3. Get Hired & Paid Faster',
    landingWorkerStep3Desc: 'Track applications, get direct offers, and secure reliable payment verification.',
    landingWorkerBtn: 'Create Your Voice Profile Now',
    landingFooterDesc: 'We didn\'t build a job app. We built an AI agent that works for the informal workforce.',
    landingFooterPlatform: 'Platform',
    landingFooterJoinWorker: 'Join as Worker',
    landingFooterJoinEmployer: 'Join as Employer',
    landingFooterHowItWorks: 'How it Works',
    landingFooterConnect: 'Connect',
    landingFooterLocation: 'Addis Ababa, Ethiopia',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
    return saved && COPY[saved] ? saved : 'en';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('language', newLang);
  };

  const value = useMemo(() => {
    const copy = COPY[lang] ?? COPY.en;
    return {
      lang,
      setLang,
      copy,
      options: Object.entries(COPY).map(([key, v]) => ({ key, label: v.label })),
    };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};