// /src/context/LanguageContext.jsx
import React, { useMemo, useState } from 'react';
import { LanguageContext } from './LanguageContextInstance.jsx';

const COPY = {
  am: {
    label: 'አማርኛ 🇪🇹',
    magicLine: 'ብቻ ይናገሩ — ስራ ስራዎችን ያገኛል፣ ያመልክታል እና ያስተያየታል።',
    micPlaceholder: 'ክህሎትዎን፣ ልምዱን እና ቦታዎን ይናገሩ…',
    headerSearchPlaceholder: 'ስራዎችን በድምፅ ወይም በጽሁፍ ይፈልጉ…',
    mapApplyCta: 'ለመመዝገብ ይናገሩ',
    ratingsTitle: 'ደረጃ እና አስተያየት',
    ratingsSubtitle: 'ለተጠናቀቁ ስራዎች ደረጃ ስጡ እና መተማመንን ያበረታቱ።',
    rateButton: 'ደረጃ ስጥ',
    voiceRatingTitle: 'የድምፅ አስተያየት',
    voiceRatingSubtitle: 'አስተያየትዎን ይናገሩ፣ ከዚያ ጽሁፉን ያስተካክሉ።',
    close: 'ዝጋ',
    cancel: 'ተወው',
    submitRating: 'ደረጃ ላክ',
    tapToSpeak: 'ለመናገር ይንኩ',
    listening: 'በማዳመጥ ላይ… አሁን ይናገሩ',
    transcribing: 'በመጻፍ ላይ…',
    feedbackLabel: 'አስተያየት',
    speakLabel: 'ይናገሩ',
    jobPostTitle: 'ስራ ለጥፍ',
    jobPostSubtitle: 'በድምፅ መጀመሪያ ስራ ማስታወቂያ፡ አንድ ጊዜ ይግለጹ፣ ስራ ቅጹን ትሞላለች።',
    voiceModeLabel: 'የድምፅ ሁነታ',
    voiceModeHint: 'ይናገሩ፡ ሚና/ስራ፣ ቦታ፣ ክፍያ፣ ቀን/ሰዓት።',
    voiceModeTap: 'ስራውን ለመግለጽ ማይኩን ይንኩ',
    voiceModeExample: 'ምሳሌ፡ “ነገ በቦሌ 2 ማጽጃ ሰራተኞች እፈልጋለሁ፣ 500 ብር።”',
    fieldTitle: 'ርዕስ',
    fieldCategory: 'ምድብ',
    fieldLocation: 'ቦታ',
    fieldSalary: 'ደመወዝ (ብር)',
    fieldDescription: 'መግለጫ',
    dashboard: 'ዳሽቦርድ',
    availableJobs: 'የሚገኙ ስራዎች',
    talkToSira: 'ከሥራ ጋር ይነጋገሩ',
    voiceToCV: 'ድምፅ ወደ ሲቪ',
    jobMap: 'የስራ ካርታ',
    history: 'ታሪክ',
    ratings: 'ደረጃዎች',
    profile: 'መገለጫ',
    employerDashboard: 'የቀጣሪ ዳሽቦርድ',
    employerSub: 'ብልጥ ማገናኛ። አስተማማኝ ውሎች። እንከን የለሽ ክፍያዎች።',
    postNewJob: 'አዲስ ስራ ልጥፍ',
    yourOpenings: 'የእርስዎ ክፍት የስራ መደቦች',
    aiMatchmaking: 'የአርቴፊሻል ኢንተለጀንስ (AI) ማገናኛ',
    topCandidates: 'ለተመረጠው ፕሮጀክት ምርጥ እጩዎች',
    noAppsFoundJob: 'ለዚህ ስራ ምንም ማመልከቻ አልተገኘም',
    postJob: 'ስራ ለጥፍ',
    applicants: 'አመልካቾች',
    adminDashboard: 'የአድሚን ዳሽቦርድ',
    scamLog: 'የማታለል ምዝገባ',
    systemLanguage: 'የስርዓት ቋንቋ',
    login: 'ግባ',
    register: 'ተመዝገብ',
    logout: 'ውጣ',
    search: 'ፈልግ',
    notifications: 'ማሳወቂያዎች',
    settings: 'ማስተካከያዎች',

    // New Dashboard / Worker Specific Keys From State Screen
    welcomeBack: 'እንኳን ደህና መጡ!',
    aiMatchingActive: 'የአርቴፊሻል ኢንተለጀንስ (AI) ማገናኛ ገባሪ ነው',
    voiceHuntingJobs: 'የእርስዎ የድምፅ ረዳት በአቅራቢያዎ ያሉ ስራዎችን እየፈለገ ነው።',
    clickVoiceSira: 'ስራ ድምፅን ለመጠቀም ይጫኑ',
    talkToFindJobs: 'ስራዎችን ለማግኘት ይናገሩ',
    weeklyEarnings: 'የሳምንት ገቢ',
    calculatedSoon: 'በቅርቡ ይሰላል',
    workerRating: 'የሰራተኛ ደረጃ',
    completedJobsCount: 'የተጠናቀቁ ስራዎች',
    activeApplications: 'ንቁ ማመልከቻዎች',
    liveFromHistory: 'ከታሪክ በቀጥታ የተወሰደ',
    bestMatchesForYou: 'ለእርስዎ ምርጥ ተዛማጆች',
    viewAll: 'ሁሉንም ይዩ',
    noMatchesYet: 'እስካሁን ምንም ተዛማጅ አልተገኘም።',
    voiceSearchMapHint: 'የድምፅ ፍለጋን ይሞክሩ ወይም ስራዎችን ለመፈለግ ካርታውን ይክፈቱ።',
    generateVoiceCv: 'የድምፅ ሲቪ (Voice-CV) ያዘጋጁ',
    voiceCvSubtitle: 'ስራ-AI ከ30 ሰከንድ የድምፅ ቅጂ የእርስዎን ሙያዊ መገለጫ እንዲገነባ ይፍቀዱለት።',
    startNow: 'አሁን ይጀምሩ',
    nearbyJobs: 'በአቅራቢያ ያሉ ስራዎች',
    openJobMap: 'የየስራ ካርታ ይክፈቱ',
    exploreJobs: 'ስራዎችን ያስሱ',
    detailsArrow: 'ዝርዝሮች →',
    speakThreeLanguagesHint: 'በአማርኛ፣ በአፋን ኦሮሞ ወይም በእንግሊዝኛ ይናገሩ። እርምጃ ከመውሰድዎ በፊት ስራ የሰማውን ማስተካከል ይችላሉ።',
    tapToSpeakHint: 'ለመናገር ይንኩ። ከ~10 ሰከንድ በኋላ በራሱ ይቆማል።',
    transcribedTextEditable: 'የተገለበጠ ጽሑፍ (ሊስተካከል የሚችል)',
    voiceBecomesCvTitle: 'የእርስዎ ድምፅ ሲቪዎ ይሆናል',
    voiceFirstCapture: 'ቀጥታ የድምፅ ቀረጻ',
    tapMicAndSpeak: 'ማይክሮፎኑን ነክተው ይናገሩ',
    whatSiraHeard: 'ስራ የሰማው',
    extractedSkills: 'የተለዩ ክህሎቶች',
    speakExampleHint1: 'እንደዚህ ማለት ይችላሉ፡ “እኔ መጋኛ አካባቢ የ3 ዓመት ልምድ ያለኝ ቧንቧ ሰራተኛ ነኝ።”',
    speakExampleHint2: '“እኔ የቤት ሰራተኛ ነኝ፣ ቦሌ እኖራለሁ…”',
    applicationHistoryTitle: 'የማመልከቻ ታሪክ',
    trackHistorySubtitle: 'እያንዳንዱን ማመልከቻ፣ ቅጥር እና ማጠናቀቂያ በአንድ ቦታ ይከታተሉ።',
    noApplicationsYet: 'እስካሁን ምንም ማመልከቻ የለም።',
    walletAndEarningsTitle: 'የእርስዎ ቦርሳ እና ገቢ',
    walletSubtitle: 'ቀሪ ሂሳብዎን፣ የሂሳብ መግለጫ ታሪክዎን ይከታተሉ እና ወደ ባንክ ማስተላለፍ ይጠይቁ።',
    withdrawFunds: 'ገንዘብ አውጣ',
    availableBalance: 'የሚገኝ ቀሪ ሂሳብ',
    readyForImmediateWithdrawal: 'ወዲያውኑ ለማውጣት ዝግጁ የሆነ',
    totalLifetimeEarned: 'በአጠቃላይ የተገኘ ጠቅላላ ገቢ',
    fromJobAllocations: 'ከተጠናቀቁ የስራ ድልድሎች የተገኘ',
    inTransferProcessing: 'በማስተላለፍ ሂደት ላይ ያለ',
    cashoutEventsAwaiting: 'በሂደት ላይ ያሉ የገንዘብ ማውጣት ክስተቶች',
    statementLedger: 'የግብይት መዝገብ መግለጫ',
    noTransactionsLogged: 'በዚህ አካውንት ላይ እስካሁን የተመዘገበ ግብይት የለም።',
    failedToLoadTransactions: 'የግብይት ታሪክን መጫን አልተሳካም',
    bioLabel: 'ስለ እኔ',
    skillsLabel: 'ክህሎቶች',
    noSkillsAdded: 'ምንም ክህሎት አልተጨመረም።',
    experienceLabel: 'የስራ ልምድ',
    yearsExperience: 'ዓመት የሥራ ልምድ',
    preferredLanguageLabel: 'የተመረጠ ቋንቋ',
    aiAgentPreferences: 'የአይ (AI) ወኪል ምርጫዎች',
    autoMatchingAndOneClick: 'ራስ-ሰር ማገናኘት እና ባለአንድ ጠቅታ ማመልከቻዎች',
    autoApplyLabel: 'ራስ-ሰር ማመልከቻ (Auto-Apply)',
    noJobSelected: 'ምንም ስራ አልተመረጠም',
    scanningDatabase: 'የመረጃ ቋቱን በመፈተሽ ላይ...',
    aiRecommendedMatch: 'በስራ የተመከረ',
    verifiedBadge: 'የተረጋገጠ',
    kmAway: 'ኪ.ሜ ርቀት',
    matchPercentage: 'ተዛማጅነት',
    hiringProgress: 'እየቀጠረ ነው...',
    hireAction: 'ቅጠር',

    // Missing Voice Assistant translation strings
    voiceAssistantSubtitle: 'በአማርኛ፣ በአፋን ኦሮሞ ወይም በእንግሊዝኛ ይናገሩ። ሥራ እርምጃ ከመውሰዱ በፊት የሰማውን ማስተካከል ይችላሉ።',
    processingVoice: 'ሥራ በማሰብ ላይ ነው…',
    autoStopHint: 'ከ~10 ሰከንድ በኋላ በራሱ ይቆማል።',
    transcribedTextLabel: 'የተቀዳ ጽሑፍ (ሊስተካከል የሚችል)',
    suggestedJobsLabel: 'የቀረቡ ሥራዎች',

    // Fallback Manual Input Text String
    typeFallbackPlaceholder: 'ትዕዛዝ ወይም የስራ መደብ እዚህ ይጻፉ…',
    saveLabel: 'ለውጦችን አስቀምጥ',
    cancelLabel: 'ሰርዝ'
  },
  or: {
    label: 'Afaan Oromoo 🇪🇹',
    magicLine: 'Dubbadhu qofa — Siiraan hojii barbaadi, galmaa’i, fi bulchi.',
    micPlaceholder: 'Dandeettii, muuxannoo, fi bakka kee dubbadhu…',
    headerSearchPlaceholder: 'Hojii sagalee ykn barreeffamaan barbaadi…',
    mapApplyCta: 'Galmaa’uuf dubbadhu',
    ratingsTitle: 'Sadarkaa & Yaada',
    ratingsSubtitle: 'Hojii xumurame irratti sadarkaa kenni; amanamummaa ijaar.',
    rateButton: 'Sadarkaa Kenni',
    voiceRatingTitle: 'Yaada Sagalee',
    voiceRatingSubtitle: 'Yaada kee dubbadhu, booda barruu sirreessi.',
    close: 'Cufi',
    cancel: 'Dhiisi',
    submitRating: 'Sadarkaa Ergi',
    tapToSpeak: 'Dubbachuuf tuqi',
    listening: 'Dhaggeeffachaa jira… amma dubbadhu',
    transcribing: 'Barreessaa…',
    feedbackLabel: 'Yaada',
    speakLabel: 'Dubbadhu',
    jobPostTitle: 'Hojii Maxxansi',
    jobPostSubtitle: 'Hojii sagalee-duraa: yeroo tokko ibsi, Siiraan guutuu foormii guuti.',
    voiceModeLabel: 'Haala Sagalee',
    voiceModeHint: 'Dubbadhu: hojii/gahee, bakka, mindaa, guyyaa/sa’aatii.',
    voiceModeTap: 'Hojii ibsuuf makiroofiin tuqi',
    voiceModeExample: 'Fakkeenya: “Bore Booletti qulqullinaa 2 barbaada, 500 birrii.”',
    fieldTitle: 'Mata-duree',
    fieldCategory: 'Gosa',
    fieldLocation: 'Bakka',
    fieldSalary: 'Mindaa (ETB)',
    fieldDescription: 'Ibsa',
    dashboard: 'Daashboordii',
    availableJobs: 'Hojii Jiran',
    talkToSira: 'Siraa wajjin dubbadhu',
    voiceToCV: 'Sagalee CV Irratti',
    jobMap: 'Kaartaa Hojii',
    history: 'Seenaa',
    ratings: 'Sadarkaa',
    profile: 'Profayilii',
    employerDashboard: 'Daashboordii Hojjeesisaa',
    employerSub: 'Walitti hidhiinsa bilchaataa. Waliigaltee amansiisaa. Kaffaltii siriitti deemuf.',
    postNewJob: 'Hojii Haaraa Baasi',
    yourOpenings: 'Banakkaawwan Hojii Keessan',
    aiMatchmaking: 'Walitti Hidhiinsa AI',
    topCandidates: 'Iyyattoota dursa qaban kan pirojektii filatameef',
    noAppsFoundJob: 'Hojii kanaaf iyyannoon argame hin jiru',
    applicants: 'Galmaa’ota',
    adminDashboard: 'Daashboordii Bulchaa',
    scamLog: 'Galmee Madaa’aa',
    systemLanguage: 'Afaan Sirnaa',
    login: 'Seeni',
    register: 'Galmaa’i',
    logout: 'Ba’i',
    search: 'Barbaadi',
    notifications: 'Beeksisa',
    settings: 'Qindaa’i',

    // New Dashboard / Worker Specific Keys From State Screen
    welcomeBack: 'Baga nagaan dhuftan!',
    aiMatchingActive: 'Walitti Hidhiinsa AI Hojii Irra Jira',
    voiceHuntingJobs: 'Eejantiin sagalee keessanii naannoo keessanitti hojii barbaadaa jira.',
    clickVoiceSira: 'Sagalee Siiraa fayyadamuuf tuqi',
    talkToFindJobs: 'Hojii argachuuf dubbadhu',
    weeklyEarnings: 'Galii Torbee',
    calculatedSoon: 'Dhiheenyatti herregama',
    workerRating: 'Sadarkaa Hojjetaa',
    completedJobsCount: 'Hojiiwwan xumuraman',
    activeApplications: 'Iyyannoo Hojii Hojjatamaa Jiru',
    liveFromHistory: 'Seenaa irraa kallattiin',
    bestMatchesForYou: 'Madaallii Gaarii Siif Ta’an',
    viewAll: 'Hunda Ilaali',
    noMatchesYet: 'Hanga ammaatti madaalliin argame hin jiru.',
    voiceSearchMapHint: 'Barbaacha sagalee yaali ykn hojiiwwan qorachuuf kaartaa banadhu.',
    generateVoiceCv: 'Voice-CV Tolchi',
    voiceCvSubtitle: 'Sira-AI waraabbii sekondi 30 irraa profaayila ogummaa kee akka ijaaru heeymamiif.',
    startNow: 'Amma Jalqabi',
    nearbyJobs: 'Hojiiwwan Dhihoo',
    openJobMap: 'Kaartaa Hojii Bani',
    exploreJobs: 'Hojiiwwan Sakatta’i',
    detailsArrow: 'Ibsa Guutuu →',
    speakThreeLanguagesHint: "Afaan Oromoo, Amharic, ykn English dubbadhu. Tarkaanfii fudhachuu dura waan Siiraan dhaga'e sirreessuu dandeessa.",
    tapToSpeakHint: 'Dubbachuuf tuqi. Sekondii ~10 booda ofiin dhaabbata.',
    transcribedTextEditable: 'Barreeffama waraabbame (gulaalamuu kan danda’u)',
    voiceBecomesCvTitle: 'Sagaleen kee CV kee ta’a',
    voiceFirstCapture: 'Waraabbii Sagalee Jalqabaa',
    tapMicAndSpeak: 'Maayikii tuquun dubbadhu',
    whatSiraHeard: 'Waan Siiraan Dhaga’e',
    extractedSkills: 'Ogummaa Baafame',
    speakExampleHint1: 'Fakkeenyaaf dubbachuuu dandeessa: “Ani hojjetaa dhaanbaa (plumber) muuxannoo waggaa 3 qabu Megenaanyatti.”',
    speakExampleHint2: '“እኔ የቤት ሰራተኛ ነኝ፣ ቦሌ እኖራለሁ…”',
    applicationHistoryTitle: 'Seenaa Iyyannoo',
    trackHistorySubtitle: 'Iyyannoo, qaxarrii fi xumura hunda bakka tokkotti hordofi.',
    noApplicationsYet: 'Hanga ammaatti iyyannoon hin jiru.',
    walletAndEarningsTitle: 'Waletii & Galii Keessan',
    walletSubtitle: 'Eeybama keessan, seenaa baasii hordofaa fi gara baankiitti kaffaltiin akka darbu gaafadha.',
    withdrawFunds: 'Maallaqa Baasi',
    availableBalance: 'Haftee Maallaqa Jiru',
    readyForImmediateWithdrawal: 'Battalatti baasuuf kan qophaaye',
    totalLifetimeEarned: 'Waliigala Maallaqa Argame',
    fromJobAllocations: 'Hojiiwwan xumuraman irraa',
    inTransferProcessing: 'Adeemsa Dabarsaa Irratti Kan Jiru',
    cashoutEventsAwaiting: 'Adeemsa baasii maallaqa eeggachaa jiru',
    statementLedger: 'Galmee Giddugaleessa daldalaa',
    noTransactionsLogged: 'Akkaawuntii kana irratti hanga ammaatti daldalli galmeeffame hin jiru.',
    failedToLoadTransactions: 'Seenaa daldalaa fiduun hin danda’amne',
    bioLabel: 'Waa’ee Koo',
    skillsLabel: 'Ogummaawwan',
    noSkillsAdded: 'Ogummaan dabalame hin jiru.',
    experienceLabel: 'Muuxannoo Hojii',
    yearsExperience: 'Waggaa muuxannoo hojii',
    preferredLanguageLabel: 'Afaan Filatame',
    aiAgentPreferences: 'Filannoo Eejansii AI',
    autoMatchingAndOneClick: 'Madaallii of-gutoof kaffaltii qofaan iyyachuu',
    autoApplyLabel: 'Ofiin Iyyadhu (Auto-Apply)',
    noJobSelected: 'Hojiin filatame hin jiru',
    scanningDatabase: 'Kuusaa daataa sakatta’aa jira...',
    aiRecommendedMatch: 'AIn Kan Mirkanae',
    verifiedBadge: 'Mirkanaa’e',
    kmAway: 'KM fagaa',
    matchPercentage: 'Madaalawaa',
    hiringProgress: 'Qaxaraa jira...',
    hireAction: 'Qaxari',

    // Missing Voice Assistant translation strings
    voiceAssistantSubtitle: "Afaan Oromoo, Amaariffa ykn Ingiliffaan dubbadhu. Sira'n gocha dura waan dhaga'e sirreessuu dandeessa.",
    processingVoice: "Sira'n yaadaa jira…",
    autoStopHint: 'Sekondii ~10 booda ofiin dhaabbata.',
    transcribedTextLabel: 'Barreeffama waraabame (kan sirreeffamu)',
    suggestedJobsLabel: 'Hojiiwwan siif dhiyaatan',

    // Fallback Manual Input Text String
    typeFallbackPlaceholder: 'Ajaja ykn gosa hojii barreessi…',
    saveLabel: 'Hanga jidduu ol-kaahi',
    cancelLabel: 'Haqi'
  },
  en: {
    label: 'English 🇬🇧',
    magicLine: 'Just speak — Sira finds, applies, and manages jobs for you.',
    micPlaceholder: 'Speak your skill, experience, and location…',
    headerSearchPlaceholder: 'Search jobs by voice or text…',
    mapApplyCta: 'Just Speak to Apply',
    ratingsTitle: 'Ratings & Feedback',
    ratingsSubtitle: 'Rate completed jobs to build trust and verified badges.',
    rateButton: 'Rate',
    voiceRatingTitle: 'Voice Rating',
    voiceRatingSubtitle: 'Speak your feedback, then adjust text if needed.',
    close: 'Close',
    cancel: 'Cancel',
    submitRating: 'Submit Rating',
    tapToSpeak: 'Tap to speak',
    listening: 'Listening… speak now',
    transcribing: 'Transcribing…',
    feedbackLabel: 'Feedback',
    speakLabel: 'Speak',
    jobPostTitle: 'Post a Job',
    jobPostSubtitle: 'Voice-first job posting: describe it once, Sira fills the form.',
    voiceModeLabel: 'Voice Mode',
    voiceModeHint: 'Speak: role, location, pay, date/time.',
    voiceModeTap: 'Tap mic to describe the job',
    voiceModeExample: 'Example: “Need 2 cleaners tomorrow in Bole, 500 birr.”',
    fieldTitle: 'Title',
    fieldCategory: 'Category',
    fieldLocation: 'Location',
    fieldSalary: 'Salary (ETB)',
    fieldDescription: 'Description',
    dashboard: 'Dashboard',
    availableJobs: 'Available Jobs',
    talkToSira: 'Talk to Sira',
    voiceToCV: 'Voice to CV',
    jobMap: 'Job Map',
    history: 'History',
    ratings: 'Ratings',
    profile: 'Profile',
    employerDashboard: 'Employer Dashboard',
    employerSub: 'Smart matching. Secure contracts. Seamless payments.',
    postNewJob: 'Post New Job',
    yourOpenings: 'Your Openings',
    aiMatchmaking: 'AI Matchmaking',
    topCandidates: 'Top candidates for selected project',
    noAppsFoundJob: 'No applications found for this job',
    applicants: 'Applicants',
    adminDashboard: 'Admin Dashboard',
    scamLog: 'Scam Log',
    systemLanguage: 'System Language',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    search: 'Search',
    notifications: 'Notifications',
    settings: 'Settings',

    // New Dashboard / Worker Specific Keys From State Screen
    welcomeBack: 'Welcome back!',
    aiMatchingActive: 'AI Matching Active',
    voiceHuntingJobs: 'Your voice agent is hunting for jobs near you.',
    clickVoiceSira: 'Click to use Sira Voice',
    talkToFindJobs: 'Talk to find jobs',
    weeklyEarnings: 'Weekly Earnings',
    calculatedSoon: 'Calculated soon',
    workerRating: 'Worker Rating',
    completedJobsCount: 'completed jobs',
    activeApplications: 'Active Applications',
    liveFromHistory: 'Live from history',
    bestMatchesForYou: 'Best Matches For You',
    viewAll: 'View All',
    noMatchesYet: 'No matches yet.',
    voiceSearchMapHint: 'Try voice search or open the map to explore jobs.',
    generateVoiceCv: 'Generate Voice-CV',
    voiceCvSubtitle: 'Let Sira-AI build your professional profile from a 30-second recording.',
    startNow: 'Start Now',
    nearbyJobs: 'Nearby Jobs',
    openJobMap: 'Open Job Map',
    exploreJobs: 'Explore Jobs',
    detailsArrow: 'Details →',
    speakThreeLanguagesHint: 'Speak in Amharic, Afaan Oromo, or English. You can edit what Sira heard before taking action.',
    tapToSpeakHint: 'Tap to speak. Auto-stops after ~10 seconds.',
    transcribedTextEditable: 'Transcribed text (editable)',
    voiceBecomesCvTitle: 'Your Voice becomes your CV',
    voiceFirstCapture: 'Voice‑First Capture',
    tapMicAndSpeak: 'Tap the mic and speak',
    whatSiraHeard: 'What Sira heard',
    extractedSkills: 'Extracted Skills',
    speakExampleHint1: 'Speak something like: “I am a plumber with 3 years experience in Megenagna.”',
    speakExampleHint2: '“እኔ የቤት ሰራተኛ ነኝ፣ ቦሌ እኖራለሁ…”',
    applicationHistoryTitle: 'Application History',
    trackHistorySubtitle: 'Track every application, hire, and completion in one place.',
    noApplicationsYet: 'No applications yet.',
    walletAndEarningsTitle: 'Your Wallet & Earnings',
    walletSubtitle: 'Track your balance, statement history, and request bank disbursements.',
    withdrawFunds: 'Withdraw Funds',
    availableBalance: 'Available Balance',
    readyForImmediateWithdrawal: 'Ready for immediate withdrawal',
    totalLifetimeEarned: 'Total Lifetime Earned',
    fromJobAllocations: 'From completed job allocations',
    inTransferProcessing: 'In Transfer Processing',
    cashoutEventsAwaiting: 'cashout events awaiting transit',
    statementLedger: 'Statement Transaction Ledger',
    noTransactionsLogged: 'No transactions logged on this account yet.',
    failedToLoadTransactions: 'Failed to load transaction history',
    bioLabel: 'Bio',
    skillsLabel: 'Skills',
    noSkillsAdded: 'No skills added.',
    experienceLabel: 'Experience',
    yearsExperience: 'years experience',
    preferredLanguageLabel: 'Preferred Language',
    aiAgentPreferences: 'AI Agent Preferences',
    autoMatchingAndOneClick: 'Auto-matching and one-click applications',
    autoApplyLabel: 'Auto-Apply',
    noJobSelected: 'No job selected',
    scanningDatabase: 'Scanning database...',
    aiRecommendedMatch: 'AI Recommended Match',
    verifiedBadge: 'Verified',
    kmAway: 'KM away',
    matchPercentage: 'Match',
    hiringProgress: 'Hiring...',
    hireAction: 'Hire',

    // Missing Voice Assistant translation strings
    voiceAssistantSubtitle: 'Speak in Amharic, Afaan Oromo, or English. You can edit what Sira heard before taking action.',
    processingVoice: 'Sira is thinking…',
    autoStopHint: 'Auto-stops after ~10 seconds.',
    transcribedTextLabel: 'Transcribed text (editable)',
    suggestedJobsLabel: 'Suggested jobs',

    // Fallback Manual Input Text String
    typeFallbackPlaceholder: 'Type command or job title manually...',
    saveLabel: 'Save Changes',
    cancelLabel: 'Cancel'
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
    return saved && COPY[saved] ? saved : 'en';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('language', newLang);
  };

  const value = useMemo(() => {
    const copy = COPY[lang] ?? COPY.en;
    return {
      lang,
      setLang,
      copy,
      options: Object.entries(COPY).map(([key, v]) => ({ key, label: v.label })),
    };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};