import React, { useMemo, useState } from 'react';
import { LanguageContext } from './LanguageContextInstance.jsx';

const COPY = {
  am: {
    label: 'አማርኛ 🇪🇹',
    magicLine: 'ብቻ ይናገሩ — ሲራ ስራዎችን ያገኛል፣ ያመልክታል እና ያስተያየታል።',
    micPlaceholder: 'ክህሎትዎን፣ ልምዱን እና ቦታዎን ይናገሩ…',
    headerSearchPlaceholder: 'ስራዎችን በድምፅ ወይም በጽሁፍ ይፈልጉ…',
    mapApplyCta: 'ለመመዝገብ ይናገሩ',
    ratingsTitle: 'ደረጃ እና አስተያየት',
    ratingsSubtitle: 'ለተጠናቀቁ ስራዎች ደረጃ ስጡ እና መተማመንን ያበረታቱ።',
    rateButton: 'ደረጃ ስጥ',
    voiceRatingTitle: 'የድምፅ አስተያየት',
    voiceRatingSubtitle: 'አስተያየትዎን ይናገሩ፣ ከዚያ ጽሁፉን ያስተካክሉ።',
    close: 'ዝጋ',
    cancel: 'ተወው',
    submitRating: 'ደረጃ ላክ',
    tapToSpeak: 'ለመናገር ይንኩ',
    listening: 'እየሰማ…',
    transcribing: 'በመጻፍ ላይ…',
    feedbackLabel: 'አስተያየት',
    speakLabel: 'ይናገሩ',
    jobPostTitle: 'ስራ ለጥፍ',
    jobPostSubtitle: 'በድምፅ መጀመሪያ ስራ ማስታወቂያ፡ አንድ ጊዜ ይግለጹ፣ ሲራ ቅጹን ትሞላለች።',
    voiceModeLabel: 'የድምፅ ሁነታ',
    voiceModeHint: 'ይናገሩ፡ ሚና/ስራ፣ ቦታ፣ ክፍያ፣ ቀን/ሰዓት።',
    voiceModeTap: 'ስራውን ለመግለጽ ማይኩን ይንኩ',
    voiceModeExample: 'ምሳሌ፡ “ነገ በቦሌ 2 ማጽጃ ሰራተኞች እፈልጋለሁ፣ 500 ብር።”',
    fieldTitle: 'ርዕስ',
    fieldCategory: 'ምድብ',
    fieldLocation: 'ቦታ',
    fieldSalary: 'ደመወዝ (ብር)',
    fieldDescription: 'መግለጫ',
    dashboard: 'ዳሽቦርድ',
    availableJobs: 'የሚገኙ ስራዎች',
    talkToSira: 'ከሲራ ይናገሩ',
    voiceToCV: 'ድምፅ ወደ ሲቪ',
    jobMap: 'የስራ ካርታ',
    history: 'ታሪክ',
    ratings: 'ደረጃዎች',
    profile: 'መገለጫ',
    employerDashboard: 'የሰራተኛ ዳሽቦርድ',
    postJob: 'ስራ ለጥፍ',
    applicants: 'አመልካቾች',
    adminDashboard: 'የአድሚን ዳሽቦርድ',
    scamLog: 'የማታ ምዝገባ',
    systemLanguage: 'የስርዓት ቋንቋ',
    login: 'ግባ',
    register: 'ተመዝገብ',
    logout: 'ውጣ',
    search: 'ፈልግ',
    notifications: 'ማሳወቂያዎች',
    settings: 'ማስተካከያዎች',
  },
  or: {
    label: 'Afaan Oromoo 🇪🇹',
    magicLine: 'Dubbadhu qofa — Siiraan hojii barbaadi, galmaa’i, fi bulchi.',
    micPlaceholder: 'Dandeettii, muuxannoo, fi bakka kee dubbadhu…',
    headerSearchPlaceholder: 'Hojii sagalee ykn barreeffamaan barbaadi…',
    mapApplyCta: 'Galmaa’uuf dubbadhu',
    ratingsTitle: 'Sadarkaa & Yaada',
    ratingsSubtitle: 'Hojii xumurame irratti sadarkaa kenni; amanamummaa ijaar.',
    rateButton: 'Sadarkaa Kenni',
    voiceRatingTitle: 'Yaada Sagalee',
    voiceRatingSubtitle: 'Yaada kee dubbadhu, booda barruu sirreessi.',
    close: 'Cufi',
    cancel: 'Dhiisi',
    submitRating: 'Sadarkaa Ergi',
    tapToSpeak: 'Dubbachuuf tuqi',
    listening: 'Dhaggeeffachaa…',
    transcribing: 'Barreessaa…',
    feedbackLabel: 'Yaada',
    speakLabel: 'Dubbadhu',
    jobPostTitle: 'Hojii Maxxansi',
    jobPostSubtitle: 'Hojii sagalee-duraa: yeroo tokko ibsi, Siiraan guutuu foormii guuti.',
    voiceModeLabel: 'Haala Sagalee',
    voiceModeHint: 'Dubbadhu: hojii/gahee, bakka, mindaa, guyyaa/sa’aatii.',
    voiceModeTap: 'Hojii ibsuuf makiroofiin tuqi',
    voiceModeExample: 'Fakkeenya: “Bore Booletti qulqullinaa 2 barbaada, 500 birrii.”',
    fieldTitle: 'Mata-duree',
    fieldCategory: 'Gosa',
    fieldLocation: 'Bakka',
    fieldSalary: 'Mindaa (ETB)',
    fieldDescription: 'Ibsa',
    dashboard: 'Daashboordii',
    availableJobs: 'Hojii Jiran',
    talkToSira: 'Siira Waliin Haasa’i',
    voiceToCV: 'Sagalee CV Irratti',
    jobMap: 'Kaartaa Hojii',
    history: 'Seenaa',
    ratings: 'Sadarkaa',
    profile: 'Profayilii',
    employerDashboard: 'Daashboordii Hojii Kennaa',
    postJob: 'Hojii Maxxansi',
    applicants: 'Galmaa’ota',
    adminDashboard: 'Daashboordii Bulchaa',
    scamLog: 'Galmee Madaa’aa',
    systemLanguage: 'Afaan Sirnaa',
    login: 'Seeni',
    register: 'Galmaa’i',
    logout: 'Ba’i',
    search: 'Barbaadi',
    notifications: 'Beeksisa',
    settings: 'Qindaa’i',
  },
  en: {
    label: 'English 🇬🇧',
    magicLine: 'Just speak — Sira finds, applies, and manages jobs for you.',
    micPlaceholder: 'Speak your skill, experience, and location…',
    headerSearchPlaceholder: 'Search jobs by voice or text…',
    mapApplyCta: 'Just Speak to Apply',
    ratingsTitle: 'Ratings & Feedback',
    ratingsSubtitle: 'Rate completed jobs to build trust and verified badges.',
    rateButton: 'Rate',
    voiceRatingTitle: 'Voice Rating',
    voiceRatingSubtitle: 'Speak your feedback, then adjust text if needed.',
    close: 'Close',
    cancel: 'Cancel',
    submitRating: 'Submit Rating',
    tapToSpeak: 'Tap to speak',
    listening: 'Listening…',
    transcribing: 'Transcribing…',
    feedbackLabel: 'Feedback',
    speakLabel: 'Speak',
    jobPostTitle: 'Post a Job',
    jobPostSubtitle: 'Voice-first job posting: describe it once, Sira fills the form.',
    voiceModeLabel: 'Voice Mode',
    voiceModeHint: 'Speak: role, location, pay, date/time.',
    voiceModeTap: 'Tap mic to describe the job',
    voiceModeExample: 'Example: “Need 2 cleaners tomorrow in Bole, 500 birr.”',
    fieldTitle: 'Title',
    fieldCategory: 'Category',
    fieldLocation: 'Location',
    fieldSalary: 'Salary (ETB)',
    fieldDescription: 'Description',
    dashboard: 'Dashboard',
    availableJobs: 'Available Jobs',
    talkToSira: 'Talk to Sira',
    voiceToCV: 'Voice to CV',
    jobMap: 'Job Map',
    history: 'History',
    ratings: 'Ratings',
    profile: 'Profile',
    employerDashboard: 'Employer Dashboard',
    applicants: 'Applicants',
    adminDashboard: 'Admin Dashboard',
    scamLog: 'Scam Log',
    systemLanguage: 'System Language',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    search: 'Search',
    notifications: 'Notifications',
    settings: 'Settings',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('language') : null;
    return saved && COPY[saved] ? saved : 'en';
  });

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('language', newLang);
  };

  const value = useMemo(() => {
    const copy = COPY[lang] ?? COPY.en;
    return {
      lang,
      setLang,
      copy,
      options: Object.entries(COPY).map(([key, v]) => ({ key, label: v.label })),
    };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

